sudo: required
services:
- docker
env:
  global:
  - BUILD_FLUENTD_VERSION=v1.9.0-1.0
  - BUILD_FLUENTD_PLUGIN_PROMETHEUS_VERSION=1.7.0
  - BUILD_VERSION=${BUILD_FLUENTD_VERSION}_${BUILD_FLUENTD_PLUGIN_PROMETHEUS_VERSION}
  - BUILD_DOCKER_TAG=${BUILD_VERSION}_${TRAVIS_BUILD_NUMBER}
  - DOCKER_USERNAME=alexandertgtalbot
  - DOCKER_NAME_SPACE=${DOCKER_USERNAME}
  - DOCKER_IMAGE_NAME=fluent-prometheus
  - secure: QB93777K8BBVjnPkEr9f2HmEzCtCi/J2MBds5TKq4W+yAAwopXRxV5/IvjIv9TmAKKlzKEEixdz5Fht50gnBDMUwoQ4RlqN0ptp6m9d1SJUmLt5MOLAfqRclE6yzvpfzIyniV/D+4zKGyXL9f4outE2dSjTNkJ1LkSo15nxCOHZqqBUCYslczsgzbUgpLdwg2GIwYSHzCiN4SP4ECnytTiESd2jBfdJULHC0hK8RzGi3WYcytpoLLA24ejRIduRUE2s/9nXQM5/sMtBxVHDwRk7AFLIWEZjZmz45p/L15PTlhR8khEhiVu2tAvUSJTnNPUYeiuy0c+VtIo8LyQVug1D6l50XOympUxIyrMqevOOODEzquwn/1OEYrPicnaP+d18iGkNa7vNJBHIoIGM9jHntw3VMUcs8IOrFEUv5+3ilJhIwQVKo+ZJo12ZcamzYdCnmXRyv3MwHagW53mw2Wn5zlmxrG7ML8W/xh0fP5AnNhVGTe1mTcv6zKINSh4qe6YgXC61I0XtJMYD2QOiTM+p51yogZsaOWpfO9RCHWVj4qh1ZLnbBaeNGOdzn159fYUcrcNLqclAgBoOhiQF2PjnhqENCMCCVPW5lUBrLzw4VXi1/fAnje2rF8dFoVzBEl+SO8J8Gf77F0nxw11dDuy6LNpSfX9Plqc+E14mSkSU=
jobs:
  include:
  - stage: Lint Dockerfile.
    script:
    - make linter
  - stage: Build Dev Docker Image and Publish to DockerHub.
    if: branch != master
    script:
    - make
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - docker tag  ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${BUILD_DOCKER_TAG} ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${BUILD_DOCKER_TAG}_dev
    - docker tag  ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${BUILD_DOCKER_TAG} ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:dev
    - docker push ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${BUILD_DOCKER_TAG}_dev
    - docker push ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:dev
    - docker logout
  - stage: Build Stable/Latest Docker Image and Publish to DockerHub.
    if: branch = master
    script:
    - make
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - docker push ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:latest
    - docker tag  ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:latest ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${BUILD_DOCKER_TAG}
    - docker push ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${BUILD_DOCKER_TAG}
    - docker logout
